### ISSUE TITLE
2a.  Access to CoCA's WordPress Server 

### ISSUE THREAD

**Issue by HTD-CoCA** [cocaseattle/artist-directory#27]

**Comment by archisgore** [comment]
Just catching up here. We won't have access to the WordPress server because we don't want to goof around in the backend. It's a hosted wordpress, and my hope is we can do everything only through the front-end. Are there specific scenarios that need the server access?

**Comment by HTD-CoCA** [comment]
I need to access the styles.css to add a picture carousel and add more css style in addition to tweaking the member profile page to retain its own images by adding the Javascript, jQuery, and PHP codes.  The hold up in the "Images Belong to Individual Files" [](https://github.com/cocaseattle/artist-directory/issues/25) issue is dependent on this.  Otherwise, do you know of a plug in (other than manually coding this feature) that we could use to resolved the "Images Belong to Individual Files" issue?

**Comment by archisgore** [comment]
Aha I see. This is good to know. Let's find a plugin. I don't know of a plugin, but if we need to build one, that's fine too. I'll do some research. Let's make this a research task.

Changing Javascript/PHP on the live server is going to not scale after we leave CoCA - future volunteers will get very confused.

**Comment by HTD-CoCA** [comment]
I will disposition this bug as invalid and close it.
