### ISSUE TITLE
12.  Obtain codes from Old Site

### ISSUE THREAD

**Issue by HTD-CoCA** [cocaseattle/artist-directory#3]
Obtain codes from the current membership website from Ray and other sources.

**Comment by archisgore** [comment]
I'm working on this right now. I don't think the code will help much. But it will provide insight into how the old stuff worked. Really my hope is with Wordpress we just start fresh and use a fully managed offering.

**Comment by archisgore** [comment]
This is the SSH Command:
```
 ssh -p 45667 -o PreferredAuthentications=password cocaseat@cocaseattle.net
```

Password available on request by texting Archis.

**Comment by HTD-CoCA** [comment]
Able to obtain access to the old server.  Closing this issue.
